### ISSUE TITLE
'ERROR: [youtube] bSFMWh9_SmI: Request format is not available' when trying to download videos

### ISSUE THREAD

**Issue by StrawberryBrains** [Shalmon123/GUIYoutube-dl#12]
![error](https://user-images.githubusercontent.com/70839227/148786305-1f8a245e-a164-450e-826c-2556e81a18f4.png)

Thank you for making this application! I however get the above error when trying to download videos, it doesn't matter whether it is in 480p, 720p or 1080p. Downloading just the audio of videos seems to work fine though!

**Comment by ShalmonAnandas** [comment]
Is the video 4:3 by any chance?

**Comment by ShalmonAnandas** [comment]
No followup
