### ISSUE TITLE
Regular Windows Download Says it's the Barebones Version? And Main EXE Doesn't Work

### ISSUE THREAD

**Issue by ZaCloud** [Shalmon123/GUIYoutube-dl#14]
Hi, uh, I don't know much about Github stuff, so maybe I'm just doing something wrong...

Anyway, I have Windows 10 (64 bit). I found the Releases, & got the Windows one (not Linux, I was careful) with the simplest name figuring it's most likely the default one (so not the Barebones or FFMPEG ones).

But when I opened the .zip file, the folder in there is called "Gui-Youtube-dl-3.1.2-barebones-ytdlp".
(Is something misnamed? Is the actual regular version one of the other ones?)

And after I extracted the folder into Program Files, I looked for "youtube-dl-gui.exe", which is what the Readme says I'm supposed to open... but there's no file by that name.

So I open "yt-dlp.exe" (which at least looks like it would be the intended program file), & a black window pops up, sits there blank momentarily, then flashes a message real quick & closes before I can read it.

I had to take several tries mashing the Print Screen button so I could finally see what it said:

```
Usage: yt-dlp.exe [OPTIONS] URL [URL...]

yt-dlp.exe: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```

So then, uh, I noticed there's another executable in there: "gui_rework.exe". I tried that, & THAT was what finally gave me the menu it seems we're supposed to get.

So um, yeah, everything seems so inconsistent & confusing here. Maybe the Readme & Release folder contents should be updated to reflect what we're actually supposed to expect & do to use this application? Thanks.

**Comment by ShalmonAnandas** [comment]
Refer my comment in issue #15
