### ISSUE TITLE
how to add cookies or user name & password ?

### ISSUE THREAD

**Issue by irabro1992** [Shalmon123/GUIYoutube-dl#7]
Hello , i also want to know that can i add cookies or username & password to gui ?
some site needed vip auth. thanks

**Comment by ShalmonAnandas** [comment]
Cookie support and custom args support is coming next update. ETA about a week.

**Comment by ShalmonAnandas** [comment]
Issue solved with commit [df1a067
](https://github.com/ShalmonAnandas/Gui-Youtube-dl/commit/df1a0677263c5bcb4e21aeefa660f94b0c289031)
