### ISSUE TITLE
Clip Downloader - Clip Setting cannot be changed

### ISSUE THREAD

**Issue by Mohammed1422** [Shalmon123/GUIYoutube-dl#8]
Hello guys! I like your gui and I used to work with the previous update.

This new update has a problem (I think just for me).
I can't change Clip Settings (the time cannot be changed and appear as a clock like AM - PM).

See the image
![Screenshot 2021-12-04 212649](https://user-images.githubusercontent.com/52231044/144720643-97879d7c-7bd6-4ed4-95bd-d8bd55806996.png)

Thanks!

**Comment by ShalmonAnandas** [comment]
Is your system clock set to 12hr format? Or 24hr format?

**Comment by Mohammed1422** [comment]
12hr format.
do not tell me this is the problem? lol

**Comment by Mohammed1422** [comment]
> Is your system clock set to 12hr format? Or 24hr format?

12hr format.
do not tell me this is the problem? lol

Update: Everything is fine, Thanks!

**Comment by ShalmonAnandas** [comment]
Did you change your computer to 24hr format? 

Ill try to fix it next patch so it works on systems.

**Comment by ShalmonAnandas** [comment]
hopefully fixed in release 3.1.2
