### ISSUE TITLE
custom argument

### ISSUE THREAD

**Issue by lulu5lulu** [Shalmon123/GUIYoutube-dl#9]
how to use custom argument?
the video I downloaded always in webm aand 720p
i want to change it to mp4 1080p

**Comment by ShalmonAnandas** [comment]
Do you have ffmpeg installed?

**Comment by ShalmonAnandas** [comment]
Bringing this project out of the dead. Any updates on your issue? or should I go ahead and close this issue

**Comment by ShalmonAnandas** [comment]
No further info provided
